import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Embodied Intelligence textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Robotic Nervous System',
      items: [{type: 'autogenerated', dirName: 'module-01-robotic-nervous-system'}],
    },
    {
      type: 'category',
      label: 'Digital Twin',
      items: [{type: 'autogenerated', dirName: 'module-02-digital-twin'}],
    },
    {
      type: 'category',
      label: 'AI Robot Brain',
      items: [{type: 'autogenerated', dirName: 'module-03-ai-robot-brain'}],
    },
    {
      type: 'category',
      label: 'Vision Language Action',
      items: [{type: 'autogenerated', dirName: 'module-04-vision-language-action'}],
    },
  ],
};

export default sidebars;
